root: "."
exclude: "\\.git"

tasks:
    echo: echo
    build:
        type: shell
        command: "go build -v -trimpath -ldflags '-s -w -X main.version=$()' -o d:/bin/fsw.exe"

triggers:
    - echo
    - { task: build, match: ["\\.go$", "!_test\\.go$"], throttle: "10s" }
